name: FrontEnd

on: [workflow_dispatch, push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: flarum/action-build@master
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
